SELECT B.AUTHOR_ID,
       AUTHOR_NAME,
       CATEGORY,
       SUM(SALES * PRICE) TOTAL_SALES
FROM BOOK B
       INNER JOIN AUTHOR A
       ON B.AUTHOR_ID = A.AUTHOR_ID
       INNER JOIN BOOK_SALES S
       ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY, A.AUTHOR_NAME
ORDER BY AUTHOR_ID, CATEGORY DESC