SELECT D1.ID
FROM ECOLI_DATA D1 LEFT JOIN ECOLI_DATA D2 ON D1.PARENT_ID = D2.ID
     LEFT JOIN ECOLI_DATA D3 ON D2.PARENT_ID = D3.ID
WHERE D2.PARENT_ID IS NOT NULL AND D3.PARENT_ID IS NULL
ORDER BY D1.ID

# ID의 PARENT_ID의 PARENT_ID의 PARENT_ID가 NULL인 것만