SELECT CAR_ID, C.CAR_TYPE,
       DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30 AS FEE
FROM (
    SELECT CAR_ID, DAILY_FEE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
) C
LEFT JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01'
      AND START_DATE <= '2022-11-30'
)
AND DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30 >= 500000
AND DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30 < 2000000
ORDER BY 1
                    

# CAR_RENTAL_COMPANY_CAR 테이블에서 '세단' 또는 'SUV' 인 경우
# 2022.11.01 ~ 2022.11.30 대여 가능
# 50만원 이상 200만원 미만 자동차