SELECT ID, CASE WHEN SIZE_GROUP = 1 THEN 'CRITICAL'
WHEN SIZE_GROUP = 2 THEN 'HIGH'
WHEN SIZE_GROUP = 3 THEN 'MEDIUM'
ELSE 'LOW' END COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) SIZE_GROUP
      FROM ECOLI_DATA) AS D
ORDER BY ID