SELECT QUARTER, COUNT(*) ECOLI_COUNT
FROM (SELECT CASE 
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
      ELSE '4Q' END AS QUARTER
      FROM ECOLI_DATA) AS T
GROUP BY QUARTER
ORDER BY QUARTER

# 1~3 -> 1분기
# 4~6 -> 2분기
# 7~9 -> 3분기
# 10~12 -> 4분기