SELECT H.HISTORY_ID,
       TRUNCATE(
           C.DAILY_FEE * H.RENTAL_DAYS
           * (100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100,
           0
       ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT HISTORY_ID,
           CAR_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS,
           CASE
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
               WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
               ELSE '7일 미만'
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H
ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
AND H.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;