SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D JOIN (SELECT CODE
                       FROM SKILLCODES
                       WHERE CATEGORY = 'Front End') S
WHERE SKILL_CODE & S.CODE = S.CODE
ORDER BY 1