SELECT MEMBER_ID,
       MEMBER_NAME,
       GENDER,
       DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO is not null AND
       substr(DATE_OF_BIRTH, 6, 2) = '03' AND
       GENDER = 'W'
ORDER BY MEMBER_ID