SELECT HR_EMPLOYEES.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_SCORE.GRADE,
      CASE WHEN HR_SCORE.GRADE = 'S' THEN HR_EMPLOYEES.SAL * 0.2
      WHEN HR_SCORE.GRADE = 'A' THEN HR_EMPLOYEES.SAL * 0.15
      WHEN HR_SCORE.GRADE = 'B' THEN HR_EMPLOYEES.SAL * 0.1
      ELSE 0 END AS BONUS
FROM (SELECT EMP_NO, AVG(SCORE) AS SCORE,
      CASE WHEN AVG(SCORE) >= 96 THEN 'S'
      WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96 THEN 'A'
      WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90 THEN 'B'
      ELSE 'C' END AS GRADE
      FROM HR_GRADE
      GROUP BY EMP_NO) AS HR_SCORE
      JOIN HR_EMPLOYEES
      ON HR_SCORE.EMP_NO = HR_EMPLOYEES.EMP_NO
ORDER BY 1 