# 부모의 등급이 RARE인 것
# PARENT_ITEM_ID에 있는 ITEM_ID의 RARITY가 RARE?

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID
                        FROM ITEM_INFO
                        WHERE RARITY = 'RARE')
ORDER BY 1 DESC