SELECT D1.ID, GENOTYPE, PARENT_GENOTYPE
FROM ECOLI_DATA D1
     LEFT JOIN (SELECT ID, GENOTYPE PARENT_GENOTYPE
          FROM ECOLI_DATA) D2
    ON D1.PARENT_ID = D2.ID
WHERE (GENOTYPE & PARENT_GENOTYPE) = PARENT_GENOTYPE
ORDER BY D1.ID