SELECT DATE_FORMAT(START_DATE, '%m') MONTH,
       CAR_ID,
       COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE between '2022-08-01' and '2022-10-31'
       AND CAR_ID IN (SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
               WHERE START_DATE between '2022-08-01' and '2022-10-31'
               GROUP BY CAR_ID
               HAVING COUNT(HISTORY_ID) >= 5)
GROUP BY MONTH, CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC