SELECT M.DIFF_YEAR YEAR, M.MAX_SIZE - E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM ECOLI_DATA E 
     JOIN (SELECT YEAR(DIFFERENTIATION_DATE) DIFF_YEAR , MAX(SIZE_OF_COLONY) MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) M
           ON YEAR(E.DIFFERENTIATION_DATE) = M.DIFF_YEAR
ORDER BY 1, 2 