SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN
       CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON
       CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND
       SUBSTR(DATE_FORMAT(HISTORY.START_DATE, '%Y-%m-%d'), 6, 2) = 10
ORDER BY 1 DESC