SELECT concat('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE F
       INNER JOIN USED_GOODS_BOARD B
       ON B.BOARD_ID = F.BOARD_ID
WHERE F.BOARD_ID = (SELECT BOARD_ID
                    FROM USED_GOODS_BOARD
                    ORDER BY VIEWS DESC
                    LIMIT 1)
ORDER BY FILE_ID DESC